vars:
  - file-paths:
      helen: data/raw/hki_dh_2015_2020_a.csv
      fmi-dir: data/raw/fmi
      prepared: data/intermediate/prepared.feather
      features: data/intermediate/features.feather
      test: data/processed/test.feather
      train: data/processed/train.feather
      model: models/model.bin
      score: output/score.json
  - fmi-station-name: 'Helsinki Kaisaniemi'

stages:
  prepare:
    cmd: >-
      python -m dh_modelling.prepare
      --input ${file-paths.helen}
      --fmi-dir ${file-paths.fmi-dir}
      --fmi-station-name "${fmi-station-name}"
      --output ${file-paths.prepared}
    deps:
      - ${file-paths.helen}
      - ${file-paths.fmi-dir}
      - dh_modelling/prepare.py
    outs:
      - ${file-paths.prepared}

  featurize:
    cmd: >-
      python -m dh_modelling.featurize
      --input ${file-paths.prepared}
      --output ${file-paths.features}
    deps:
      - ${file-paths.prepared}
      - dh_modelling/featurize.py
    outs:
      - ${file-paths.features}

  split:
    cmd: >-
      python -m dh_modelling.split
      --input ${file-paths.features}
      --test-size ${prepare.split}
      --train-output ${file-paths.train}
      --test-output ${file-paths.test}
    deps:
      - ${file-paths.features}
      - dh_modelling/split.py
    outs:
      - ${file-paths.train}
      - ${file-paths.test}

  train:
    cmd: >-
      python -m dh_modelling.train
      --train-path ${file-paths.train}
      --model-path ${file-paths.model}
      --optimize-rounds ${train.optimize-rounds}
      --num-boost-round ${train.num-boost-round}
      --use-gpu
    deps:
      - ${file-paths.train}
      - dh_modelling/train.py
    outs:
      - ${file-paths.model}

  evaluate:
    cmd: >-
      python -m dh_modelling.evaluate
      --model-path ${file-paths.model}
      --test-path ${file-paths.test}
      --metrics-path ${file-paths.score}
    deps:
      - ${file-paths.model}
      - ${file-paths.test}
      - dh_modelling/evaluate.py
    metrics:
      - ${file-paths.score}
