vars:
  - file-paths:
      helen: data/raw/hki_dh_2015_2020_a.csv
      fmi-dir: data/raw/fmi
      test: data/processed/test.feather
      master: data/processed/master.feather
  - fmi-station-name: 'Helsinki Kaisaniemi'
stages:
  prepare:
    cmd: >-
      python dh_modelling/data/prepare_data.py
      --split ${prepare.split}
      --helen-path ${file-paths.helen}
      --fmi-dir ${file-paths.fmi-dir}
      --fmi-station-name "${fmi-station-name}"
      --test-path ${file-paths.test}
      --master-path ${file-paths.master}
    deps:
    - ${file-paths.helen}
    - ${file-paths.fmi-dir}
    - dh_modelling/data/prepare_data.py
    outs:
    - ${file-paths.test}
    - ${file-paths.master}
